Update DG (Logic)
AY2223S2-CS2103T-W15-2/tp pull request #154
Opened 2023-03-21 18:51 UTC by chongweiguan

Closes #153

2023-03-22 06:45 UTC, HmuuMyatMoe requested changes
Good work, just need to add some information to some of the diagrams.

2023-03-22 06:45 UTC, HmuuMyatMoe commented on docs/images/DeleteSequenceDiagram.png
The method that DeleteOrderCommand calls should be deleteOrder(1) instead of deletePerson(1)

2023-03-22 06:45 UTC, HmuuMyatMoe commented on docs/images/LogicClassDiagram.png
The diagram should show the association between LogicManager and TrackrParser since LogicManager has a reference to 1 TrackrParser

Also, maybe it would be good to show that LogicManager implements the interface Logic?
(I think the interface Parser should be replaced with the interface Logic instead)

2023-03-22 06:45 UTC, HmuuMyatMoe commented on docs/images/ParserClasses.png
Labelling some of the associations like that done for AB3 would be better.

Dependency between TrackrParser and Command and the dependency between ArgumentTokenizer and ArgumentMultimap is missing.

2023-03-23 23:54 UTC, LiuMC-SG requested changes
The diagrams look fixed, but can they be exported in svg format to remove blurriness

2023-03-24 04:18 UTC, LiuMC-SG approved these changes
LGTM

2023-03-24 04:18 UTC, merged